### ISSUE TITLE
hello marcelstoer

### ISSUE THREAD

**Issue by edgiru** [marcelstoer/nodemcu-custom-build#15]
Your project is very interesting. I have one question. Tell us how you arranged assembly firmware online? I think this way: github-docker-bootstrap-generate scripts-docker-github = to email firmware.

Tell us how the whole mechanism is arranged? if it `s not a secret :))

bootstrap can put your converted into open access here?

**Comment by marcelstoer** [comment]
It's a lot easier... PHP on my host - GitHub API - Travis CI - FTPS to upload firmware - PHP on my host to send email.
