### ISSUE TITLE
Allow to configure ADC

### ISSUE THREAD

**Issue by marcelstoer** [marcelstoer/nodemcu-custom-build#18]
http://nodemcu.readthedocs.org/en/dev/en/modules/adc/
https://github.com/nodemcu/nodemcu-firmware/blob/dev/app/include/user_config.h#L16

**Comment by janitz** [comment]
would be an awsome enhancement! :)

**Comment by marcelstoer** [comment]
Will become obsolete once[ NodeMCU PR 1285](https://github.com/nodemcu/nodemcu-firmware/pull/1285) has landed.
