### ISSUE TITLE
feature request: blynk module

### ISSUE THREAD

**Issue by sjoerdtimmer** [marcelstoer/nodemcu-custom-build#20]
There is a very cool project: http://www.blynk.cc/
Inclusion of their c module in lua would be neat. It shouldn't be difficult to wrap in lua.

**Comment by marcelstoer** [comment]
> It shouldn't be difficult to wrap in lua.

Great, the NodeMCU team is looking forward to a pull request from you then at https://github.com/nodemcu/nodemcu-firmware/pulls.
