### ISSUE TITLE
math library omits log, sin, cos, etc

### ISSUE THREAD

**Issue by PomDev2** [marcelstoer/nodemcu-custom-build#28]
The website build is not linking most of the math functions into the binaries. What's available is minimal, e.g.,  [for key,value in pairs(math) do print(key) end .. abs ceil floor max min pow random randomseed sqrt pi huge] . Missing are the log and trig functions, etc. I found a web page on this topic: "fix missing math library compilation error on Linux:" https://github.com/hellerve/e/pull/35

Also the site support FAQ "send me an email" link opens up a "reCAPTCHA V1 IS SHUTDOWN" popup, so the support email address is not available. I am including this in the hope you can help fix this problem.

In the meantime, one workaround is to implement, for example, an approximate log function of the "y = (v1 - 1) / (v1 + 1)" variety, which actually works pretty well, and is not that large.

**Comment by marcelstoer** [comment]
If at all it'd rather be a bug in the firmware than in the cloud builder. However, those functions were deliberately omitted in the firmware to reduce memory footprint. See https://github.com/nodemcu/nodemcu-firmware/issues/1280 and https://github.com/nodemcu/nodemcu-firmware/blob/master/app/lua/lmathlib.c.

Thanks for the reCAPTCHA hint, will fix that.
