### ISSUE TITLE
Web UI support for LFS

### ISSUE THREAD

**Issue by TerryE** [marcelstoer/nodemcu-custom-build#29]
Supersedes #27.

Marcel, I would like the CBS to support LFS builds roughly concurrent to its release into dev.   We therefore need to have menu option to support cloud builds with the following parameters:

Variable | Option
----------|------------
LUA_FLASH_STORE **n** | This must be set to use LFS.  Even a selection (disabled, 32Kb, 64Kb, 94Kb) would be a good start.
SPIFFS_MAX_FILESYSTEM_SIZE n<br>SPIFFS_FIXED_LOCATION n | Fixed location SPIFFS images are pretty much essential for rapid `spiffsimg` generation.  I suggest that you allow users to optionally set the max filesystem size in multiples of 64Kb and set the fixed location to 0x100000 if the size is set.

Note that as per your suggestion, I have dropped the suggestion that we expose LUA_PACK_TVALUES as an option. This  drops the size of `TValues` from 16 byte to 12 for floating point builds, saving a lot of RAM.  It seems solid and has no downsides so why expose this to cloud builder users?  use 12 or 16 byte.

I will assume that you will generate the following parameters in build_config:

-  `flash_store`:  Integer parameter = no of Kb in LFS.  Valid values are 0..128 Kb (for now).
-  `spiffs_base`:  Integer parameter = base address in Kb in SPIFFS image.
-  `spiffs_size`:   Integer parameter = no of Kb in SPIFFS image size. 

All of these must be a 4Kb multiple.  In all cased 0 implies the default, e.g. no LFS is configured, SPIFFS starts immediately after the firmware, SPIFFS will occupy all free Flash. 

I will raise the PR for the build scripts.

**Comment by marcelstoer** [comment]
How about this https://nodemcu-build.com/LFS-options.mov?  I've yet to find a few quiet hours to actually try this marvel (LFS)!
