### ISSUE TITLE
Allow copy/paste emails

### ISSUE THREAD

**Issue by RenaKunisaki** [marcelstoer/nodemcu-custom-build#32]
It's 2018, our browsers automatically fill in the email field. Being forced to copy it by hand is only going to cause *more* typos.

**Comment by mk-pmb** [comment]
Please have a lookt at `build.config`, line 1:

> email=suvft@rkpvgr.pbz

and the occurrences of `X_EMAIL` in `.travis.yml` for how to build without having to re-enter your mail address.
I agree that the Web UI could be a lot cooler, but I think it's good enough for one-shot builds. For to-be-repeated builds, I'm working on [a github action](https://github.com/mk-pmb/nodemcu-build-as-github-action) to build them.

**Comment by marcelstoer** [comment]
> I'm working on a github action to build them.

I'm curious to see how that turns out. Go for it! 👍 

> For to-be-repeated builds...

... all you need are probably two to cURL statements (never tried). Just sayin' 😜

**Comment by mk-pmb** [comment]
It seems to work now. At least it builds something and provides it as artifact for download. Anyone who already has custom build config header files, and an expectation of what the firmware download should be or do, please give it a try.

https://github.com/mk-pmb/nodemcu-firmware-daily-vanilla/

**Comment by marcelstoer** [comment]
The repeat-email field is history.
