### ISSUE TITLE
Include more details in email?

### ISSUE THREAD

**Issue by nfriedly** [marcelstoer/nodemcu-custom-build#8]
Hey, would it be possible to include the list of modules (and fonts!) in the email that gets sent out for each build?

Oh, and thanks for creating this, BTW - much easier than figuring things out on my own!

**Comment by marcelstoer** [comment]
While the list of modules is already included in the emails you got today at 20:19, 20:57, and 21:08 the list of fonts isn't. Since most people don't use the u8g module (reference: http://frightanic.com/nodemcu-custom-build/stats.php) the list of fonts would be of no use to them.

Even though I won't be adding the font list to the email any time soon I keep this issue open.

**Comment by nfriedly** [comment]
Oh, doh, it was hidden behind Gmail's "show quoted text".

And, yea, the font list only makes sense when u8g is included.

**Comment by marcelstoer** [comment]
> it was hidden behind Gmail's "show quoted text"

Would be interesting to know what exactly makes Google think that'd be quoted text.

**Comment by nfriedly** [comment]
Well, it probably wasn't hidden in the first one, but I did 3 builds in a
row and selected the same options each time. Then later I wanted to figure
out which fonts I had selected and if I had included some module...

On Sat, Aug 1, 2015 at 4:49 PM, Marcel Stör notifications@github.com
wrote:

> it was hidden behind Gmail's "show quoted text"
> 
> Would be interesting to know what exactly makes Google think that'd be
> quoted text.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcelstoer/nodemcu-custom-build/issues/8#issuecomment-126952879
> .

## 

Nathan Friedly
Minister, JavaScript Ninjaneer
http://nfriedly.com

**Comment by marcelstoer** [comment]
We're now fast approaching build number 50'000 and this request has never come up again -> closing.
